name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o main
      
    - name: Run
      run: go run main

    #- name: Test
    #  run: go test -v ./...
    
    - name: Commit changes
      run: |
         git config --local user.email "frankxjkuang@gmail.com"
         git config --local user.name "frankj"
         git add .
         git commit -m "update wallpaper"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.bing-wallpaper }}
         branch: main
